import type { Metadata } from "next";
import { Noto_Sans_Arabic, Poppins } from "next/font/google";
import "./globals.css";
import LangProvider from "./Hooks/LangHook/LangHook";
import MainClientLayout from "./MainClientLayout";
import ThemeProvider from "./Hooks/ThemeHook/ThemeProvider";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-en",
});

const notoArabic = Noto_Sans_Arabic({
  subsets: ["arabic"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-ar",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${notoArabic.variable} antialiased`}>
        <LangProvider>
          <MainClientLayout>
            <ThemeProvider>
              {children}
            </ThemeProvider>
          </MainClientLayout>
        </LangProvider>
      </body>
    </html>
  );
}